### ISSUE TITLE
format-shell failed with code 1.

### ISSUE THREAD

**Issue by leagris** [focusaurus/atom-format-shell#7]
Atom 1.30.0 x64 Linux
format-shell 2.0.0
shfmt_v2.5.1_linux_amd64

format-shell failed with code 1.

:147:28: test operator words must consist of a single literal
```Bash
    if [[ "$(confirmUser)" =~^${LMUSER}|(?![aA](?:[bB][oO][rR][tT])?|[qQ]|[xX]|)$ ]];
```

Fails at the `=` sign.

**Comment by focusaurus** [comment]
Looks like you are missing a space after `=~` so the formatter can't parse your script. Try fixing that then formatting.

**Comment by focusaurus** [comment]
I tried your snippet in a test file, reproduced the error, added the missing space, then was able to format the script.

**Comment by leagris** [comment]
Thank you, I thought the errors were those of the pluggin ^^

**Comment by focusaurus** [comment]
Right, this message is the formatter saying "I can't format this script because it has this syntax error". This plugin is strictly about formatting. I recommend also installing the `linter` atom plugin and `linter-shellcheck`, which will check your script for syntax errors (and other common issues) and highlight them for you as you type. Then once your code passes lint, you can autoformat it.
